
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/PROGRA~2/MICROS~2/18/BUILDT~1/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-4.1/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Windows - 10.0.26200 - AMD64
...
